### ISSUE TITLE
Remove CONFIG_CMA_SIZE_MBYTES from config

### ISSUE THREAD

**Issue by bzub** [gokrazy/kernel#139]
https://github.com/gokrazy/kernel/blob/660e72919556ce428a3366172245cd0d4a810d01/cmd/gokr-build-kernel/build.go#L54

Looks like the patch to defconfig is in kernel v4.19.x so maybe this can be removed now.

https://github.com/torvalds/linux/blob/84df9525b0c27f3ebc2ebb1864fa62a97fdedb7d/arch/arm64/configs/defconfig#L174

**Comment by stapelberg** [comment]
Thanks for the heads-up. Would you like to send a PR to remove the line so that the change is properly attributed?

**Comment by bzub** [comment]
Yah, will do
