### ISSUE TITLE
Smaller kernel config ?

### ISSUE THREAD

**Issue by anisse** [gokrazy/kernel#153]
Hi,

Currently the config runs make defconfig, which generates uses the default combined arm64 defconfig. Is the goal of this project to make a generic kernel, than could work on multiple devices, or is the scope limited to the raspberry pi 3?

If it's the latest, would you be open to a reduced defconfig with less platforms supported ?

Similarly, if the goal is to support more boards, wouldn't the kernel image (without modules) grow a bit big ? 

Last but not least, is adding more drivers for use with rpi3 in scope ? I'm thinking of this:
https://github.com/anisse/beatbox-kernel/commit/f597f35750fa1703a81bef621056225faaec3237 (it needs more testing though before I can submit any PR).

I realize opening an issue is suboptimal for asking questions, but it seemed the best option to discuss this in public.

**Comment by stapelberg** [comment]
> Currently the config runs make defconfig, which generates uses the default combined arm64 defconfig. Is the goal of this project to make a generic kernel, than could work on multiple devices, or is the scope limited to the raspberry pi 3?

The scope is limited to devices which are explicitly tested on real hardware. See also https://gokrazy.org/platforms.html for details. I’m trying to keep the support matrix intentionally small: the supported Raspberry Pi variants represents the most popular, reasonably cheap, ARM single-board computer, the APU represents a reasonably standard PC platform. This should cover a large number of use-cases, while still being a manageable number of devices to test and maintain.

> Last but not least, is adding more drivers for use with rpi3 in scope

Yeah. I’ll happily merge requests to enable any in-tree driver that doesn’t have any obvious downsides (e.g. breaking existing functionality).

**Comment by stapelberg** [comment]
I’ll close this issue as there’s nothing to be done immediately, but the general stance still stands: we can enable additional kernel config options where needed. We also have support for loadable kernel modules these days.
