### ISSUE TITLE
EPD driver for Papirus screen support ?

### ISSUE THREAD

**Issue by CaptnMoutarde** [gokrazy/kernel#233]
Hi !
I am currently working on a project and I would like to use gokrazy for a minimalist system. 
I need to use a Papirus screen device ad i spent a lot of time to target piece of code i have to change to make it work.

The best option I came up with for now is to modify the gokr-rebuild-kernel to install the drivers (still in progress...) with docker.

What do you think about that ?

**Comment by stapelberg** [comment]
If the driver is part of Linux (i.e. no extra patches needed) and all you need to do is a config change, that’s fine. Feel free to submit a PR.

**Comment by CaptnMoutarde** [comment]
Yes I wanted to do that in the first place but it is not part of linux. The installation procedure is as follow (section : install fuse driver) : 
-> https://github.com/wmarbut/go-epdfuse

I wasn't aware about linux driver's module so I made some research and thouth I could clone the git driver repository (https://github.com/repaper/gratis/tree/master) and made a custom linux kernel.
But the driver code is different from other driver I saw and no KConfig file.

So for now, the only option I see is to use docker to follow the install procedure if I'm not misunderstanding something. I'll post as soon as I get something !

**Comment by stapelberg** [comment]
The repaper/gratis repository contains an LCD driver program (not a kernel module, a program) which offers a FUSE file system interface to control the LCD.

Getting this setup to work on gokrazy will not be trivial, especially for a beginner. I would recommend you try simpler examples first, then check out https://gokrazy.org/prototyping.html.

The gokrazy way would be to implement an LCD driver in native Go (which will then be easy to deploy to gokrazy). https://github.com/repaper/gratis/blob/27f245ed4a4ff391b721a0a30c7f952b2266a690/PlatformWithOS/driver-common/epd_fuse.c seems to be a good starting point.

**Comment by CaptnMoutarde** [comment]
Thanks !

I kept going to find a way and i found this issue on the repaper git rep : 
https://github.com/repaper/gratis/issues/68

So the driver is now part of linux in : "drivers/gpu/drm/tiny" folder.
So I changed the AddendumConfig variable in the gokr-rebuild-kernel bin to match the recquired config variable but nothing seems to happen. I expected to find the framebuffer in the /dev folder but nothing is created.

I thought it was because the SPI interface wasn't enable wich I did by adding the config variable but nothing too.

Am I misunderstanding the process ?

**Comment by stapelberg** [comment]
> So I changed the AddendumConfig variable in the gokr-rebuild-kernel bin to match the recquired config variable but nothing seems to happen.

Just to double-check: did you re-install gokr-rebuild-kernel and run gokr-rebuild-kernel? Can you show a `git diff` of your changes to the github.com/gokrazy/kernel package?

> I expected to find the framebuffer in the /dev folder but nothing is created.

Can you check if the options you enabled are present in `/proc/config.gz` on your gokrazy device? That should narrow down whether you’re running the modified kernel or not. If the variable is present, perhaps checking the `dmesg` output contains a clue as to what the driver is doing.
