### ISSUE TITLE
gokrazy-build-kernel fails if podman-docker compat binary is installed

### ISSUE THREAD

**Issue by fxkr** [gokrazy/kernel#258]
Fedora package podman-docker provides a docker binary that emulates docker functionality, but is actually a wrapper around podman. If this is installed, then gokrazy-rebuild-kernel fails.

The reason is that it detects "docker", and therefore elides `--userns=keep-id`, leading to the owner of `/tmp/buildresult` (as seen inside the container) staying `root`, and since the directory is 700 copying vmlinuz to the directory will fail.

Not sure if you'd consider this a bug in gokrazy - one could say it's more a bug in podman-docker. I just wanted to bring this to your atttention since it took me a while to figure this out, in case you'd like to document or hack around it (for example, by probing for podman before docker), but I don't mind if you decide to just close as not a bug. Obviously this can easily be worked around via `dnf remove podman-docker`.

podman & podman-docker version: 2:1.9.0-1.fc31

`gokr-rebuild-kernel` output:
```
...
  OBJCOPY arch/arm64/boot/Image
  GZIP    arch/arm64/boot/Image.gz
2020/05/09 02:57:13 open /tmp/buildresult/vmlinuz: permission denied
2020/05/08 19:57:16 docker run: exit status 1 (cmd: [/usr/bin/docker run --rm --volume /tmp/gokr-rebuild-kernel653178216:/tmp/buildresult:Z gokr-rebuild-kernel])
```

**Comment by stapelberg** [comment]
Thanks for reporting this!

We actually already have podman-specific code:
https://github.com/gokrazy/kernel/blob/82e30a7d5160d27b7725f28d7eada4894fc2a4e5/cmd/gokr-rebuild-kernel/kernel.go#L103

…so maybe that could be extended to construct a valid podman invocation? Would you be able to send a PR that fixes this?
