### ISSUE TITLE
Unable to build custom kernel config

### ISSUE THREAD

**Issue by brutella** [gokrazy/kernel#511]
**On Linux**
I've updated the configAddendum  in `cmd/gokr-build-kernel/build.go` and added the following config options.

```
CONFIG_MEDIA_SUPPORT=y
CONFIG_VIDEO_DEV=m
CONFIG_VIDEO_V4L2_COMMON=m
CONFIG_VIDEO_MEDIA=m
CONFIG_VIDEO_V4L2=m
CONFIG_VIDEO_CAPTURE_DRIVERS=y
CONFIG_V4L_USB_DRIVERS=y
CONFIG_USB_VIDEO_CLASS=m
CONFIG_USB_VIDEO_CLASS_INPUT_EVDEV=y
```

Then I've installed `gokr-build-kernel` with `go install ./cmd/...`. When I try to execute `gokr-rebuild-kernel`, I get the error `exec format error`.

```
2023/05/23 14:44:34 building docker container for kernel compilation
Sending build context to Docker daemon 5.492 MB
Step 0 : FROM debian:buster
 ---> 8e1e14d63347
Step 1 : RUN apt-get update && apt-get install -y crossbuild-essential-arm64 bc libssl-dev bison flex kmod
 ---> Running in 5c93bd2c0fd4
exec format error
[8] System error: exec format error
2023/05/23 14:44:37 docker build: exit status 1 (cmd: [docker build --rm=true --tag=gokr-rebuild-kernel .])
```

**On maOS**
When I try the steps from above on macOS 12.5, I get the error `go: cannot install cross-compiled binaries when GOBIN is set` because of https://github.com/gokrazy/kernel/blob/main/cmd/gokr-rebuild-kernel/kernel.go#L141-L144

Any ideas?

**Comment by stapelberg** [comment]
> Then I've installed `gokr-build-kernel` with `go install ./cmd/...`. When I try to execute `gokr-rebuild-kernel`, I get the error `exec format error`.

Which architecture are you running this on? Can you paste the output of `go env` please?

I tried and the build works for me on an amd64 Linux machine:

```
% go install ./cmd/...
% gokr-rebuild-kernel 
2023/05/26 10:01:01 building podman container for kernel compilation
STEP 1/10: FROM debian:buster
STEP 2/10: RUN apt-get update && apt-get install -y crossbuild-essential-arm64 bc libssl-dev bison flex kmod
--> Using cache 688f015b377f5ed1067a8bdf594daa20a22dde4d118b999d7e0b717bc42579f0
--> 688f015b377
STEP 3/10: COPY gokr-build-kernel /usr/bin/gokr-build-kernel
--> 8ad0c952427
[…]
```

**Comment by stapelberg** [comment]
> When I try the steps from above on macOS 12.5, I get the error `go: cannot install cross-compiled binaries when GOBIN is set` because of https://github.com/gokrazy/kernel/blob/main/cmd/gokr-rebuild-kernel/kernel.go#L141-L144

You could try to remove the GOBIN= variable and then adjust the path below in https://github.com/gokrazy/kernel/blob/7b9516483a3d8f0398901996a1d93c29f909081d/cmd/gokr-rebuild-kernel/kernel.go#L148

**Comment by brutella** [comment]
> You could try to remove the GOBIN= variable ...

I've tried that and it didn't work. I wasn't able to cross-compile `gokr-build-kernel` using `go install`. Using `go build` instead worked though.

**Comment by stapelberg** [comment]
I pushed https://github.com/gokrazy/kernel/commit/cd8a16f481e00f2a7c4821bbc174dddb60270ed9 to help with the `go build` issue. With that, I can successfully build a gokrazy kernel on macOS (MacBook Air M1) in about 10 minutes.

Regarding the question about the modules: I went through the options you list, but some of them don’t exist (anymore?), while others are not supposed to be used (MEDIA_SUPPORT_FILTER hides the options), and others just don’t work as a module (or at least not with the remaining kernel config). Where did you get these options from? Maybe they are tied to a specific kernel version, like the Raspberry Pi foundation fork?

In general, I recommend working with Linux’s `make menuconfig`. So, for gokrazy, prepare a checkout with the same `.config` file (we should probably offer a flag in `gokr-build-kernel` to make this easier), then run `make ARCH=arm64 menuconfig`. Compare the resulting `.config` with the one from before to know how your config addendum has to look. Use the `/` key to search for kernel options.

**Comment by brutella** [comment]
Thanks for the change. I'm now able to build the kernel on macOS. After a lot of research, I finally "found" the correct config flags to access the USB webcam using uvcvideo.
```
CONFIG_MEDIA_SUPPORT=y
CONFIG_MEDIA_CAMERA_SUPPORT=y
CONFIG_MEDIA_USB_SUPPORT=y
CONFIG_USB=y
CONFIG_VIDEO_DEV=y
CONFIG_USB_VIDEO_CLASS=m
```

By setting `CONFIG_USB_VIDEO_CLASS=m`, I get the uvcvideo module which I can then load with `modprobe uvcvideo`.

**Comment by brutella** [comment]
The size difference between the kernel with `uvcvideo`/`v4l2` support and the standard kernel is 2.448,953 kB. See https://github.com/brutella/kernel/commit/a21341f8fed53da4862c26f74f7eea434140fea8

**Comment by stapelberg** [comment]
Only 388 KB of that go into vmlinuz, the rest goes into the loadable kernel modules. That’s reasonable, I think — could you send a PR to add your config addendum? Thanks.

**Comment by brutella** [comment]
Sure → #514
