### ISSUE TITLE
Enable policy routing

### ISSUE THREAD

**Issue by mutantmonkey** [gokrazy/kernel#555]
Currently, Tailscale will not configure IPv6 on the tailscale0 interface. This is because it checks to see if policy routing is supported, and if it is not, it will not configure IPv6: https://github.com/tailscale/tailscale/blob/5812093d31c8a7f9c5e3a455f0fd20dcc011d8cd/util/linuxfw/linuxfw.go#L134

It should be possible to turn policy routing on by setting these two config options:
```
CONFIG_IP_MULTIPLE_TABLES=y
CONFIG_IPV6_MULTIPLE_TABLES=y
```

I'll hopefully have a chance to try this out in the next couple of days. If successful, is this something that can be added to this kernel?

**Comment by stapelberg** [comment]
Yeah, sounds reasonable. Thanks!
